### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by chaenu** [Sebastian-Fitzner/veams-cli#1]
There's an error on OSX when trying to run veams:

```
$ veams
env: node\r: No such file or directory
```

I suppose this is due to a conflict with the different line endings in unix/dos. Any idea how to fix this best?

Related:
https://github.com/nwjs/nw-builder/issues/75
http://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo
https://help.github.com/articles/dealing-with-line-endings/

**Comment by Sebastian-Fitzner** [comment]
Okay, will be fixed asap... Thx for the hint.

**Comment by Sebastian-Fitzner** [comment]
Can you update your package with `veams update` and check if it is working now?

**Comment by brennanMKE** [comment]
I am seeing this happen when I install the latest beta. Has this been fixed? Is there a commit for it?

**Comment by Sebastian-Fitzner** [comment]
It is fixed in the latest version ... Tested it on a fresh Ubuntu system.
