### ISSUE TITLE
Error when installing a bower-component with custom name

### ISSUE THREAD

**Issue by chaenu** [Sebastian-Fitzner/veams-cli#3]
Hey,

as discussed: 
I wanted to install a bower-component and ran `veams -i bc veams-component-accordion accordion-veams`. The component got installed correctly, but there were some errors afterwards in my project, because the custom name was not applied correctly. 
- All folders were generated as expected (e.g. /templating/partials/components/accordion-veams/ or js/modules/accordion-veams/)
- The files were generated with the wrong name (e.g. /templating/partials/components/accordion-veams/c-accordion.hbs or js/modules/accordion-veams/accordion.js)
- The component README.md was generated with the wrong name (Accordion instead of Accordion-veams), also the whole documentation
- And therefore the wrong paths were included at the insert points (e.g. "import Accordion from './modules/accordion/accordion';" - I expected "import AccordionVeams from './modules/accordion-veams/accordion-vems';"). This led to the error described.

Thanks!

**Comment by Sebastian-Fitzner** [comment]
This stuff is too special. The installation works as it is, no module name mapping included...
