### ISSUE TITLE
Custom installation fails due to yeoman error (?)

### ISSUE THREAD

**Issue by chaenu** [Sebastian-Fitzner/veams-cli#4]
Hey,

there's an error when using the custom installation routine. The minimal one works fine.

Used versions:
Node.js: v6.0.0
generator-veams: 6.7.3
veams-cli: 1.2.20
inserter: 1.0.4

The error happens after selecting the js libraries (see below). Same error happens on a windows machine. 

> Custom installation routine selected.
> 
> ? Your project name test2
> ? Would you mind telling me your name? thomas
> ? Which task runner do you want to use? (Press <space> to select)Grunt
> ? Which Grunt-Plugins do you want to use? (Press <space> to select)grunt-autoprefixer, grunt-browser-sync, grunt-browserify, grunt-combine-mq, grunt-dr-svg-sprites, grunt-version
> ? Which Template Engine do you want to install? Assemble
> ? Do you want to install Assemble-Plugins? No
> ? Do you want to use Extended Layouts in Assemble? No
> ? Do you want to use any Sass Frameworks? (Press <space> to select)
> ? Do you want to use any JS Libraries? 
> ❯◉ jQuery (latest Version)
>  ◯ BackboneJS
>  ◯ Exoskeleton
>  ◯ Ampersand (can only be used with CommonJS)
>  ◯ document-register-element
> 
> /usr/local/lib/node_modules/veams-cli/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:77
>     throw e;
>     ^
> true

Any idea what's going on?

**Comment by Sebastian-Fitzner** [comment]
I guess it is a problem with the new node version. There are some major breaking changes, so a variety of projects needs a bit time to update the code base,

But you can test if your build is successful when using a previous node version ... 

Furthermore it is a problem of generator-veams, so it would be awesome if you can transfer the ticket over

**Comment by chaenu** [comment]
This issue was moved to Sebastian-Fitzner/generator-veams#63
