### ISSUE TITLE
Name Error at Minmal Installation (bower.json)

### ISSUE THREAD

**Issue by Sw0rdiX** [Sebastian-Fitzner/veams-cli#5]
Hi,

think this error happens because no name is set in the bower.json if u choose the minimal installation.
but installation is successfully in the end.

> I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.
> 
> bower                         EINVALID Failed to read …/bower.json
> 
> Additional error details:
> No "name" property set

Greetz,
SWX

**Comment by Sebastian-Fitzner** [comment]
Any suggestion for a default name?

**Comment by Sebastian-Fitzner** [comment]
This problem is fixed in the latest version (1.2.22).
