### ISSUE TITLE
Option to change data-css attribute of components to a common css inheritance

### ISSUE THREAD

**Issue by IOIO72** [Sebastian-Fitzner/veams-cli#6]
_Background:_
I like the data-css construction for base css classes very much, but there are some developing clients, who don't agree to that. To benefit from the Veams CLI there should be an option to switch the base class methodology of components like as follows.
1. The default option is the current data-css concept.
2. The alternative option should switch the mode to the following code generation:

_HBS:_

```
<div class="c-input-field {{#if inputFieldContextClass}}context--{{inputFieldContextClass}}{{/if}}{{#if inputFieldClasses}} {{inputFieldClasses}}{{/if}}">
    ...
</div>
```

_SCSS:_

```
.c-input-field {
    ...
    /* ---------------------------------------------------
    Context: Sidebar
    --------------------------------------------------- */
    &.context--sidebar {
        ...
    }
}
```

In this case I removed the "default" context, but it could also remain...

**Comment by Sebastian-Fitzner** [comment]
Veams-Cli is flexible enough to support your behavior. 

You just need to provide a custom template. 
Reference the new templates in the Config file. 
That's it...

I can post an example if you like.
