### ISSUE TITLE
remove command for veams-cli

### ISSUE THREAD

**Issue by IOIO72** [Sebastian-Fitzner/veams-cli#7]
A remove command could be be handy, if you added a component or block that isn't needed anymore.
The remove command should remove all files and insertations of the component or block.

**Comment by Sebastian-Fitzner** [comment]
Sounds like a good idea ... will check it.

**Comment by Sebastian-Fitzner** [comment]
After some research the result is, that this handling can be really expensive. Will not be implemented!
