### ISSUE TITLE
Merging options from helpers/config.js

### ISSUE THREAD

**Issue by HenriPodolski** [Sebastian-Fitzner/veams-cli#8]
Currently you are using:  
```
"veams": {
        "configFile": "helpers/config.js"
    },
```
which does not require the correct file.

Please use this, because this worked on my machine (note the ./):
```
"veams": {
        "configFile": "./helpers/config.js"
    },
```

**Comment by Sebastian-Fitzner** [comment]
Sure, will be added ... thx!

**Comment by Sebastian-Fitzner** [comment]
Issue fixed in upcoming version ...
